name = "StochasticPDE"
version = "0.1.0"
defaultTargets = ["StochasticPDE"]

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "721b21cf2bbec8f5709aa776c9f0238a80c8568a"

[[lean_lib]]
name = "StochasticPDE"